SELECT NOW.*
     , (SELECT SUM(A1.JYUCHU_SP) FROM SYU_KI_JYUCHU_SP_TBL A1 WHERE A1.ANKEN_ID = NOW.ANKEN_ID AND A1.RIREKI_ID = NOW.RIREKI_ID AND A1.DATA_KBN = 'K' AND A1.SYUEKI_YM < '201903S') AS JYUCHU_SP_B_RUIKEI
     , (  NVL((SELECT A1.JYUCHU_SP FROM SYU_KI_JYUCHU_SP_TBL A1 WHERE A1.ANKEN_ID = NOW.ANKEN_ID AND A1.RIREKI_ID = NOW.RIREKI_ID AND A1.DATA_KBN = 'M' AND A1.SYUEKI_YM = '201812'), 0)
       - (SELECT A1.JYUCHU_SP FROM SYU_KI_JYUCHU_SP_TBL A1 WHERE A1.ANKEN_ID = NOW.ANKEN_ID AND A1.RIREKI_ID = NOW.RIREKI_ID AND A1.DATA_KBN = 'J' AND A1.SYUEKI_YM = '201812')
       )
       AS JYUCHU_SP_TM


     /*IF zenkaiRirekiId != null*/
     , NVL(NOW.JYUCHU_SP_K1, 0) - BEF.JYUCHU_SP_K1 AS JYUCHU_SP_K1_DIFF
     , NVL(NOW.JYUCHU_SP_K2, 0) - BEF.JYUCHU_SP_K2 AS JYUCHU_SP_K2_DIFF
     , NVL(NOW.JYUCHU_SP_G, 0) - BEF.JYUCHU_SP_G   AS JYUCHU_SP_G_DIFF
     , NVL(NOW.JYUCHU_SP_1Q, 0) - BEF.JYUCHU_SP_1Q AS JYUCHU_SP_1Q_DIFF
     , NVL(NOW.JYUCHU_SP_2Q, 0) - BEF.JYUCHU_SP_2Q AS JYUCHU_SP_2Q_DIFF
     , NVL(NOW.JYUCHU_SP_3Q, 0) - BEF.JYUCHU_SP_3Q AS JYUCHU_SP_3Q_DIFF
     , NVL(NOW.JYUCHU_SP_4Q, 0) - BEF.JYUCHU_SP_4Q AS JYUCHU_SP_4Q_DIFF
     /*END*/

     
  FROM (SELECT A.ANKEN_ID
             , A.RIREKI_ID
             , A.CURRENCY_CODE
             , A.DISP_SEQ
             -- Žó’ƒŒ[ƒg
             , SUM(CASE WHEN A.SYUEKI_YM = '201810' THEN A.JYUCHU_RATE END) AS JYUCHU_RATE_1
             , SUM(CASE WHEN A.SYUEKI_YM = '201811' THEN A.JYUCHU_RATE END) AS JYUCHU_RATE_2
             , SUM(CASE WHEN A.SYUEKI_YM = '201812' THEN A.JYUCHU_RATE END) AS JYUCHU_RATE_3
             , SUM(CASE WHEN A.SYUEKI_YM = '201901' THEN A.JYUCHU_RATE END) AS JYUCHU_RATE_4
             , SUM(CASE WHEN A.SYUEKI_YM = '201902' THEN A.JYUCHU_RATE END) AS JYUCHU_RATE_5
             , SUM(CASE WHEN A.SYUEKI_YM = '201903' THEN A.JYUCHU_RATE END) AS JYUCHU_RATE_6
             , SUM(CASE WHEN A.SYUEKI_YM = '201904' THEN A.JYUCHU_RATE END) AS JYUCHU_RATE_7
             , SUM(CASE WHEN A.SYUEKI_YM = '201905' THEN A.JYUCHU_RATE END) AS JYUCHU_RATE_8
             , SUM(CASE WHEN A.SYUEKI_YM = '201906' THEN A.JYUCHU_RATE END) AS JYUCHU_RATE_9
             , SUM(CASE WHEN A.SYUEKI_YM = '201907' THEN A.JYUCHU_RATE END) AS JYUCHU_RATE_10
             , SUM(CASE WHEN A.SYUEKI_YM = '201908' THEN A.JYUCHU_RATE END) AS JYUCHU_RATE_11
             , SUM(CASE WHEN A.SYUEKI_YM = '201909' THEN A.JYUCHU_RATE END) AS JYUCHU_RATE_12
             , SUM(CASE WHEN A.DATA_KBN = 'Q' AND A.SYUEKI_YM = '201812Q' THEN A.JYUCHU_RATE END) AS JYUCHU_RATE_1Q
             , SUM(CASE WHEN A.DATA_KBN = 'Q' AND A.SYUEKI_YM = '201903Q' THEN A.JYUCHU_RATE END) AS JYUCHU_RATE_2Q
             , SUM(CASE WHEN A.DATA_KBN = 'K' AND A.SYUEKI_YM = '201903S' THEN A.JYUCHU_RATE END) AS JYUCHU_RATE_K1
             , SUM(CASE WHEN A.DATA_KBN = 'Q' AND A.SYUEKI_YM = '201906Q' THEN A.JYUCHU_RATE END) AS JYUCHU_RATE_3Q
             , SUM(CASE WHEN A.DATA_KBN = 'Q' AND A.SYUEKI_YM = '201909Q' THEN A.JYUCHU_RATE END) AS JYUCHU_RATE_4Q
             , SUM(CASE WHEN A.DATA_KBN = 'K' AND A.SYUEKI_YM = '201909K' THEN A.JYUCHU_RATE END) AS JYUCHU_RATE_K2
             , SUM(CASE WHEN A.DATA_KBN = 'G' THEN A.JYUCHU_RATE END) AS JYUCHU_RATE_G
             -- Žó’SP
             , SUM(CASE WHEN A.SYUEKI_YM = '201810' THEN A.JYUCHU_SP END) AS JYUCHU_SP_1
             , SUM(CASE WHEN A.SYUEKI_YM = '201811' THEN A.JYUCHU_SP END) AS JYUCHU_SP_2
             , SUM(CASE WHEN A.SYUEKI_YM = '201812' THEN A.JYUCHU_SP END) AS JYUCHU_SP_3
             , SUM(CASE WHEN A.SYUEKI_YM = '201901' THEN A.JYUCHU_SP END) AS JYUCHU_SP_4
             , SUM(CASE WHEN A.SYUEKI_YM = '201902' THEN A.JYUCHU_SP END) AS JYUCHU_SP_5
             , SUM(CASE WHEN A.SYUEKI_YM = '201903' THEN A.JYUCHU_SP END) AS JYUCHU_SP_6
             , SUM(CASE WHEN A.SYUEKI_YM = '201904' THEN A.JYUCHU_SP END) AS JYUCHU_SP_7
             , SUM(CASE WHEN A.SYUEKI_YM = '201905' THEN A.JYUCHU_SP END) AS JYUCHU_SP_8
             , SUM(CASE WHEN A.SYUEKI_YM = '201906' THEN A.JYUCHU_SP END) AS JYUCHU_SP_9
             , SUM(CASE WHEN A.SYUEKI_YM = '201907' THEN A.JYUCHU_SP END) AS JYUCHU_SP_10
             , SUM(CASE WHEN A.SYUEKI_YM = '201908' THEN A.JYUCHU_SP END) AS JYUCHU_SP_11
             , SUM(CASE WHEN A.SYUEKI_YM = '201909' THEN A.JYUCHU_SP END) AS JYUCHU_SP_12
             , SUM(CASE WHEN A.DATA_KBN = 'Q' AND A.SYUEKI_YM = '201812Q' THEN A.JYUCHU_SP END) AS JYUCHU_SP_1Q
             , SUM(CASE WHEN A.DATA_KBN = 'Q' AND A.SYUEKI_YM = '201903Q' THEN A.JYUCHU_SP END) AS JYUCHU_SP_2Q
             , SUM(CASE WHEN A.DATA_KBN = 'K' AND A.SYUEKI_YM = '201903S' THEN A.JYUCHU_SP END) AS JYUCHU_SP_K1
             , SUM(CASE WHEN A.DATA_KBN = 'Q' AND A.SYUEKI_YM = '201906Q' THEN A.JYUCHU_SP END) AS JYUCHU_SP_3Q
             , SUM(CASE WHEN A.DATA_KBN = 'Q' AND A.SYUEKI_YM = '201909Q' THEN A.JYUCHU_SP END) AS JYUCHU_SP_4Q
             , SUM(CASE WHEN A.DATA_KBN = 'K' AND A.SYUEKI_YM = '201909K' THEN A.JYUCHU_SP END) AS JYUCHU_SP_K2
             , SUM(CASE WHEN A.DATA_KBN = 'G' THEN A.JYUCHU_SP END) AS JYUCHU_SP_G
          FROM (SELECT NVL(J.ANKEN_ID, A.ANKEN_ID)           AS ANKEN_ID
                     , NVL(J.RIREKI_ID, A.RIREKI_ID)         AS RIREKI_ID
                     , NVL(J.CURRENCY_CODE, A.CURRENCY_CODE) AS CURRENCY_CODE
                     , J.DATA_KBN
                     , J.SYUEKI_YM
                     , (SELECT C.DISP_SEQ FROM SYU_CUR_MST C WHERE C.CURRENCY_CODE = NVL(J.CURRENCY_CODE, A.CURRENCY_CODE)) AS DISP_SEQ
                     , J.JYUCHU_RATE
                     , J.JYUCHU_SP
                  FROM (SELECT *
                          FROM SYU_KI_JYUCHU_SP_TBL J1
                         WHERE J1.ANKEN_ID = 'S70000466138'
                           AND J1.RIREKI_ID = 0) J

                         full outer join

                       (SELECT A1.ANKEN_ID
                             , A1.RIREKI_ID
                             , A1.CURRENCY_CODE
                          FROM SYU_KI_SP_CUR_TBL A1
                         WHERE A1.ANKEN_ID = 'S70000466138'
                           AND A1.RIREKI_ID = 0
                         GROUP BY A1.ANKEN_ID, A1.RIREKI_ID, A1.CURRENCY_CODE)  A

                          on (J.ANKEN_ID = A.ANKEN_ID AND J.RIREKI_ID = A.RIREKI_ID AND J.CURRENCY_CODE = A.CURRENCY_CODE)

                 WHERE A.ANKEN_ID IS NOT NULL
                    OR (  (   J.DATA_KBN IN ('J', 'M') AND J.SYUEKI_YM BETWEEN '201810' AND '201909' 
                          AND (  (J.DATA_KBN = 'J' AND J.SYUEKI_YM < '201901')
                              OR (J.DATA_KBN = 'M' AND J.SYUEKI_YM >= '201901')
                              )
                          )
                       OR (J.DATA_KBN = 'Q' AND J.SYUEKI_YM IN ('201812Q', '201903Q', '201906Q', '201909Q'))
                       OR (J.DATA_KBN = 'K' AND J.SYUEKI_YM IN ('201903S', '201909K'))
                       OR (J.DATA_KBN = 'G')
                       )
               ) A
        GROUP BY A.ANKEN_ID, A.RIREKI_ID, A.CURRENCY_CODE, A.DISP_SEQ
       ) NOW


        LEFT OUTER JOIN
      (SELECT B.ANKEN_ID
            , B.RIREKI_ID
            , B.CURRENCY_CODE
            , SUM(CASE WHEN B.DATA_KBN = 'K' AND SYUEKI_YM = '201903S' THEN B.JYUCHU_SP END) AS JYUCHU_SP_K1
            , SUM(CASE WHEN B.DATA_KBN = 'K' AND SYUEKI_YM = '201909K' THEN B.JYUCHU_SP END) AS JYUCHU_SP_K2
            , SUM(CASE WHEN B.DATA_KBN = 'G' THEN B.JYUCHU_SP END) AS JYUCHU_SP_G
            , SUM(CASE WHEN B.DATA_KBN = 'Q' AND SYUEKI_YM = '201812Q' THEN B.JYUCHU_SP END) AS JYUCHU_SP_1Q
            , SUM(CASE WHEN B.DATA_KBN = 'Q' AND SYUEKI_YM = '201903Q' THEN B.JYUCHU_SP END) AS JYUCHU_SP_2Q
            , SUM(CASE WHEN B.DATA_KBN = 'Q' AND SYUEKI_YM = '201906Q' THEN B.JYUCHU_SP END) AS JYUCHU_SP_3Q
            , SUM(CASE WHEN B.DATA_KBN = 'Q' AND SYUEKI_YM = '201909Q' THEN B.JYUCHU_SP END) AS JYUCHU_SP_4Q
         FROM SYU_R_KI_JYUCHU_SP_TBL B
        WHERE ANKEN_ID = 'S70000466138'
          AND RIREKI_ID = :zenkaiRirekiId
          AND (
                 (B.DATA_KBN = 'G')
                 OR
                 (B.DATA_KBN = 'K' AND B.SYUEKI_YM IN ('201903S', '201909K'))
                 OR
                 (B.DATA_KBN = 'Q' AND B.SYUEKI_YM IN ('201812Q', '201903Q', '201906Q', '201909Q'))
              )
       GROUP BY B.ANKEN_ID, B.RIREKI_ID, B.CURRENCY_CODE
      ) BEF ON NOW.ANKEN_ID = BEF.ANKEN_ID AND NOW.CURRENCY_CODE = BEF.CURRENCY_CODE


ORDER BY NOW.DISP_SEQ
